import { ICertificateField } from '../models/certificate.model';

// Default certificate templates configuration
export const DEFAULT_TEMPLATES = [
	{
		name: 'Attendance Certificate',
		description: 'Standard certificate for event attendees',
		templateType: 'generated' as const,
		fields: [
			{
				id: 'title',
				name: 'Certificate Title',
				type: 'text' as const,
				x: 50,
				y: 20,
				fontSize: 32,
				fontFamily: 'Arial',
				color: '#1a365d',
				required: true,
			},
			{
				id: 'participantName',
				name: 'Participant Name',
				type: 'text' as const,
				x: 50,
				y: 40,
				fontSize: 24,
				fontFamily: 'Arial',
				color: '#2d3748',
				required: true,
			},
			{
				id: 'eventName',
				name: 'Event Name',
				type: 'text' as const,
				x: 50,
				y: 55,
				fontSize: 18,
				fontFamily: 'Arial',
				color: '#4a5568',
				required: true,
			},
			{
				id: 'eventDate',
				name: 'Event Date',
				type: 'date' as const,
				x: 50,
				y: 65,
				fontSize: 14,
				fontFamily: 'Arial',
				color: '#718096',
				required: true,
			},
			{
				id: 'organizerSignature',
				name: 'Organizer Signature',
				type: 'text' as const,
				x: 70,
				y: 85,
				fontSize: 12,
				fontFamily: 'Arial',
				color: '#2d3748',
				required: false,
			},
		],
		defaultValues: {
			title: 'Certificate of Attendance',
		},
	},
	{
		name: 'Speaker Certificate',
		description: 'Certificate for event speakers and presenters',
		templateType: 'generated' as const,
		fields: [
			{
				id: 'title',
				name: 'Certificate Title',
				type: 'text' as const,
				x: 50,
				y: 20,
				fontSize: 32,
				fontFamily: 'Arial',
				color: '#744210',
				required: true,
			},
			{
				id: 'participantName',
				name: 'Speaker Name',
				type: 'text' as const,
				x: 50,
				y: 40,
				fontSize: 24,
				fontFamily: 'Arial',
				color: '#2d3748',
				required: true,
			},
			{
				id: 'recognition',
				name: 'Recognition Text',
				type: 'text' as const,
				x: 50,
				y: 50,
				fontSize: 16,
				fontFamily: 'Arial',
				color: '#4a5568',
				required: true,
			},
			{
				id: 'eventName',
				name: 'Event Name',
				type: 'text' as const,
				x: 50,
				y: 60,
				fontSize: 18,
				fontFamily: 'Arial',
				color: '#4a5568',
				required: true,
			},
			{
				id: 'eventDate',
				name: 'Event Date',
				type: 'date' as const,
				x: 50,
				y: 70,
				fontSize: 14,
				fontFamily: 'Arial',
				color: '#718096',
				required: true,
			},
			{
				id: 'organizerSignature',
				name: 'Organizer Signature',
				type: 'text' as const,
				x: 70,
				y: 85,
				fontSize: 12,
				fontFamily: 'Arial',
				color: '#2d3748',
				required: false,
			},
		],
		defaultValues: {
			title: 'Certificate of Recognition',
			recognition: 'for outstanding contribution as a speaker',
		},
	},
	{
		name: 'Volunteer Certificate',
		description: 'Certificate for event volunteers',
		templateType: 'generated' as const,
		fields: [
			{
				id: 'title',
				name: 'Certificate Title',
				type: 'text' as const,
				x: 50,
				y: 20,
				fontSize: 32,
				fontFamily: 'Arial',
				color: '#22543d',
				required: true,
			},
			{
				id: 'participantName',
				name: 'Volunteer Name',
				type: 'text' as const,
				x: 50,
				y: 40,
				fontSize: 24,
				fontFamily: 'Arial',
				color: '#2d3748',
				required: true,
			},
			{
				id: 'appreciation',
				name: 'Appreciation Text',
				type: 'text' as const,
				x: 50,
				y: 50,
				fontSize: 16,
				fontFamily: 'Arial',
				color: '#4a5568',
				required: true,
			},
			{
				id: 'eventName',
				name: 'Event Name',
				type: 'text' as const,
				x: 50,
				y: 60,
				fontSize: 18,
				fontFamily: 'Arial',
				color: '#4a5568',
				required: true,
			},
			{
				id: 'eventDate',
				name: 'Event Date',
				type: 'date' as const,
				x: 50,
				y: 70,
				fontSize: 14,
				fontFamily: 'Arial',
				color: '#718096',
				required: true,
			},
			{
				id: 'organizerSignature',
				name: 'Organizer Signature',
				type: 'text' as const,
				x: 70,
				y: 85,
				fontSize: 12,
				fontFamily: 'Arial',
				color: '#2d3748',
				required: false,
			},
		],
		defaultValues: {
			title: 'Certificate of Appreciation',
			appreciation: 'for dedicated volunteer service',
		},
	},
	{
		name: 'Participation Certificate',
		description: 'General participation certificate for all roles',
		templateType: 'generated' as const,
		fields: [
			{
				id: 'title',
				name: 'Certificate Title',
				type: 'text' as const,
				x: 50,
				y: 20,
				fontSize: 32,
				fontFamily: 'Arial',
				color: '#553c9a',
				required: true,
			},
			{
				id: 'participantName',
				name: 'Participant Name',
				type: 'text' as const,
				x: 50,
				y: 40,
				fontSize: 24,
				fontFamily: 'Arial',
				color: '#2d3748',
				required: true,
			},
			{
				id: 'participantRole',
				name: 'Participant Role',
				type: 'text' as const,
				x: 50,
				y: 50,
				fontSize: 16,
				fontFamily: 'Arial',
				color: '#4a5568',
				required: true,
			},
			{
				id: 'eventName',
				name: 'Event Name',
				type: 'text' as const,
				x: 50,
				y: 60,
				fontSize: 18,
				fontFamily: 'Arial',
				color: '#4a5568',
				required: true,
			},
			{
				id: 'eventDate',
				name: 'Event Date',
				type: 'date' as const,
				x: 50,
				y: 70,
				fontSize: 14,
				fontFamily: 'Arial',
				color: '#718096',
				required: true,
			},
			{
				id: 'organizerSignature',
				name: 'Organizer Signature',
				type: 'text' as const,
				x: 70,
				y: 85,
				fontSize: 12,
				fontFamily: 'Arial',
				color: '#2d3748',
				required: false,
			},
		],
		defaultValues: {
			title: 'Certificate of Participation',
		},
	},
];

// Certificate color templates
export const CERTIFICATE_TEMPLATES = [
	{
		id: 'template-1',
		name: 'Classic Blue',
		description: 'Professional blue gradient design',
		colors: {
			primary: '#1e40af',
			secondary: '#3b82f6',
			accent: '#60a5fa',
			text: '#1f2937',
		},
		style: 'classic',
	},
	{
		id: 'template-2',
		name: 'Elegant Purple',
		description: 'Sophisticated purple theme',
		colors: {
			primary: '#7c3aed',
			secondary: '#a855f7',
			accent: '#c084fc',
			text: '#1f2937',
		},
		style: 'elegant',
	},
	{
		id: 'template-3',
		name: 'Modern Green',
		description: 'Fresh green modern design',
		colors: {
			primary: '#059669',
			secondary: '#10b981',
			accent: '#34d399',
			text: '#1f2937',
		},
		style: 'modern',
	},
	{
		id: 'template-4',
		name: 'Warm Orange',
		description: 'Vibrant orange energy theme',
		colors: {
			primary: '#ea580c',
			secondary: '#f97316',
			accent: '#fb923c',
			text: '#1f2937',
		},
		style: 'warm',
	},
	{
		id: 'template-5',
		name: 'Royal Gold',
		description: 'Luxurious gold premium design',
		colors: {
			primary: '#d97706',
			secondary: '#f59e0b',
			accent: '#fbbf24',
			text: '#1f2937',
		},
		style: 'royal',
	},
];
